on: [push]

name: Haskell build

jobs:
  build:
    name: Build the package
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        ghc: ['8.10', '9.0', '9.2']
        os: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v2

      - name: Cache Haskell dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
              ${{ runner.os }}-${{ matrix.ghc }}-
              ${{ runner.os }}-

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Build
        run: cabal build all
